options:
  zenml_logging_verbosity:
    description: |
      The logging verbosity of ZenDesk Server
    type: string
    default: "DEBUG"
  zenml_port:
    description: |
      The port ZenDesk Server will be listening on
    type: int
    default: 8080
  zenml_nodeport:
    description: |
      The nodeport for ZenDesk Server
    type: int
    default: 31375
  enable_zenml_nodeport:
    description: Deploy the NodePort service for ZenDesk Server
    type: boolean
    default: true
  cpu:
    description: |
      K8s cpu resource limit, e.g. "1" or "500m". Default is unset (no limit).
      See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    type: string
  memory:
    description: |
      K8s memory resource limit, e.g. "1Gi". Default is unset (no limit).
      See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    type: string
